// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "TCH001",
    name: "Md. Abdul Rahman",
    email: "abdul.rahman@school.edu.bd",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01712345678",
    subjects: ["Mathematics", "Geometry"],
    classes: ["1B", "2A", "3C"],
    address: "Dhanmondi, Dhaka-1205, Bangladesh",
  },
  {
    id: 2,
    teacherId: "TCH002",
    name: "Fatema Begum",
    email: "fatema.begum@school.edu.bd",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01723456789",
    subjects: ["Physics", "Chemistry"],
    classes: ["5A", "4B", "3C"],
    address: "Gulshan, Dhaka-1212, Bangladesh",
  },
  {
    id: 3,
    teacherId: "TCH003",
    name: "Dr. Mohammad Ali",
    email: "mohammad.ali@school.edu.bd",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01734567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "Uttara, Dhaka-1230, Bangladesh",
  },
  {
    id: 4,
    teacherId: "TCH004",
    name: "Nusrat Jahan",
    email: "nusrat.jahan@school.edu.bd",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01745678901",
    subjects: ["History"],
    classes: ["5A", "4B", "3C"],
    address: "Banani, Dhaka-1213, Bangladesh",
  },
  {
    id: 5,
    teacherId: "TCH005",
    name: "Rashida Khatun",
    email: "rashida.khatun@school.edu.bd",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01756789012",
    subjects: ["Music", "History"],
    classes: ["5A", "4B", "3C"],
    address: "Wari, Dhaka-1203, Bangladesh",
  },
  {
    id: 6,
    teacherId: "TCH006",
    name: "Prof. Ahmed Hossain",
    email: "ahmed.hossain@school.edu.bd",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01767890123",
    subjects: ["Physics"],
    classes: ["5A", "4B", "3C"],
    address: "Mirpur, Dhaka-1216, Bangladesh",
  },
  {
    id: 7,
    teacherId: "TCH007",
    name: "Karim Uddin",
    email: "karim.uddin@school.edu.bd",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01778901234",
    subjects: ["English", "Bengali"],
    classes: ["5A", "4B", "3C"],
    address: "Old Dhaka, Dhaka-1100, Bangladesh",
  },
  {
    id: 8,
    teacherId: "TCH008",
    name: "Nasreen Akter",
    email: "nasreen.akter@school.edu.bd",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01789012345",
    subjects: ["Mathematics", "Geometry"],
    classes: ["5A", "4B", "3C"],
    address: "Khilgaon, Dhaka-1219, Bangladesh",
  },
  {
    id: 9,
    teacherId: "TCH009",
    name: "Dr. Selina Begum",
    email: "selina.begum@school.edu.bd",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01790123456",
    subjects: ["Literature", "English"],
    classes: ["5A", "4B", "3C"],
    address: "Rampura, Dhaka-1219, Bangladesh",
  },
  {
    id: 10,
    teacherId: "TCH010",
    name: "Mohammad Hasan",
    email: "mohammad.hasan@school.edu.bd",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01701234567",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "Tejgaon, Dhaka-1208, Bangladesh",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "STU001",
    name: "Arif Hossain",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01711111111",
    grade: 5,
    class: "1B",
    address: "Dhanmondi, Dhaka-1205, Bangladesh",
  },
  {
    id: 2,
    studentId: "STU002",
    name: "Fatima Akter",
    email: "fatima.akter@student.edu.bd",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01722222222",
    grade: 5,
    class: "5A",
    address: "Gulshan, Dhaka-1212, Bangladesh",
  },
  {
    id: 3,
    studentId: "STU003",
    name: "Rakib Ahmed",
    email: "rakib.ahmed@student.edu.bd",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01733333333",
    grade: 5,
    class: "5A",
    address: "Uttara, Dhaka-1230, Bangladesh",
  },
  {
    id: 4,
    studentId: "STU004",
    name: "Nusrat Jahan",
    email: "nusrat.jahan@student.edu.bd",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01744444444",
    grade: 5,
    class: "5A",
    address: "Banani, Dhaka-1213, Bangladesh",
  },
  {
    id: 5,
    studentId: "STU005",
    name: "Sadia Rahman",
    email: "sadia.rahman@student.edu.bd",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01755555555",
    grade: 5,
    class: "5A",
    address: "Wari, Dhaka-1203, Bangladesh",
  },
  {
    id: 6,
    studentId: "STU006",
    name: "Tahmid Hasan",
    email: "tahmid.hasan@student.edu.bd",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01766666666",
    grade: 5,
    class: "5A",
    address: "Mirpur, Dhaka-1216, Bangladesh",
  },
  {
    id: 7,
    studentId: "STU007",
    name: "Rashida Begum",
    email: "rashida.begum@student.edu.bd",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01777777777",
    grade: 5,
    class: "5A",
    address: "Old Dhaka, Dhaka-1100, Bangladesh",
  },
  {
    id: 8,
    studentId: "STU008",
    name: "Karim Uddin",
    email: "karim.uddin@student.edu.bd",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01788888888",
    grade: 5,
    class: "5A",
    address: "Khilgaon, Dhaka-1219, Bangladesh",
  },
  {
    id: 9,
    studentId: "STU009",
    name: "Nasrin Akter",
    email: "nasrin.akter@student.edu.bd",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01799999999",
    grade: 5,
    class: "5A",
    address: "Rampura, Dhaka-1219, Bangladesh",
  },
  {
    id: 10,
    studentId: "STU010",
    name: "Mohammad Ali",
    email: "mohammad.ali@student.edu.bd",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01700000000",
    grade: 5,
    class: "5A",
    address: "Tejgaon, Dhaka-1208, Bangladesh",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "Md. Abdul Hossain",
    students: ["Arif Hossain"],
    email: "abdul.hossain@parent.edu.bd",
    phone: "01711111110",
    address: "Dhanmondi, Dhaka-1205, Bangladesh",
  },
  {
    id: 2,
    name: "Fatema Begum",
    students: ["Fatima Akter"],
    email: "fatema.begum@parent.edu.bd",
    phone: "01722222220",
    address: "Gulshan, Dhaka-1212, Bangladesh",
  },
  {
    id: 3,
    name: "Ahmed Ali",
    students: ["Rakib Ahmed"],
    email: "ahmed.ali@parent.edu.bd",
    phone: "01733333330",
    address: "Uttara, Dhaka-1230, Bangladesh",
  },
  {
    id: 4,
    name: "Nusrat Jahan",
    students: ["Nusrat Jahan", "Tahmid Hasan"],
    email: "nusrat.jahan@parent.edu.bd",
    phone: "01744444440",
    address: "Banani, Dhaka-1213, Bangladesh",
  },
  {
    id: 5,
    name: "Rashida Khatun",
    students: ["Sadia Rahman"],
    email: "rashida.khatun@parent.edu.bd",
    phone: "01755555550",
    address: "Wari, Dhaka-1203, Bangladesh",
  },
  {
    id: 6,
    name: "Prof. Mohammad Hasan",
    students: ["Tahmid Hasan"],
    email: "mohammad.hasan@parent.edu.bd",
    phone: "01766666660",
    address: "Mirpur, Dhaka-1216, Bangladesh",
  },
  {
    id: 7,
    name: "Karim Uddin",
    students: ["Rashida Begum", "Nasrin Akter"],
    email: "karim.uddin@parent.edu.bd",
    phone: "01777777770",
    address: "Old Dhaka, Dhaka-1100, Bangladesh",
  },
  {
    id: 8,
    name: "Nasreen Akter",
    students: ["Karim Uddin"],
    email: "nasreen.akter@parent.edu.bd",
    phone: "01788888880",
    address: "Khilgaon, Dhaka-1219, Bangladesh",
  },
  {
    id: 9,
    name: "Dr. Selina Begum",
    students: ["Nasrin Akter", "Mohammad Ali"],
    email: "selina.begum@parent.edu.bd",
    phone: "01799999990",
    address: "Rampura, Dhaka-1219, Bangladesh",
  },
  {
    id: 10,
    name: "Mohammad Ali",
    students: ["Mohammad Ali"],
    email: "mohammad.ali@parent.edu.bd",
    phone: "01700000000",
    address: "Tejgaon, Dhaka-1208, Bangladesh",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Mathematics",
    teachers: ["Md. Abdul Rahman", "Nasreen Akter"],
  },
  {
    id: 2,
    name: "English",
    teachers: ["Karim Uddin", "Dr. Selina Begum"],
  },
  {
    id: 3,
    name: "Bengali",
    teachers: ["Karim Uddin", "Dr. Selina Begum"],
  },
  {
    id: 4,
    name: "Physics",
    teachers: ["Fatema Begum", "Prof. Ahmed Hossain"],
  },
  {
    id: 5,
    name: "Chemistry",
    teachers: ["Fatema Begum"],
  },
  {
    id: 6,
    name: "Biology",
    teachers: ["Dr. Mohammad Ali", "Mohammad Hasan"],
  },
  {
    id: 7,
    name: "History",
    teachers: ["Nusrat Jahan", "Rashida Khatun"],
  },
  {
    id: 8,
    name: "Geography",
    teachers: ["Nusrat Jahan"],
  },
  {
    id: 9,
    name: "Islamic Studies",
    teachers: ["Rashida Khatun"],
  },
  {
    id: 10,
    name: "General Science",
    teachers: ["Dr. Mohammad Ali", "Mohammad Hasan"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Md. Abdul Rahman",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Fatema Begum",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Dr. Mohammad Ali",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Nusrat Jahan",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Rashida Khatun",
  },
  {
    id: 6,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Prof. Ahmed Hossain",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Karim Uddin",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Nasreen Akter",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Dr. Selina Begum",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Mohammad Hasan",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Mathematics",
    class: "1A",
    teacher: "Md. Abdul Rahman",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Karim Uddin",
  },
  {
    id: 3,
    subject: "Bengali",
    class: "3A",
    teacher: "Dr. Selina Begum",
  },
  {
    id: 4,
    subject: "General Science",
    class: "1B",
    teacher: "Dr. Mohammad Ali",
  },
  {
    id: 5,
    subject: "Islamic Studies",
    class: "4A",
    teacher: "Rashida Khatun",
  },
  {
    id: 6,
    subject: "History",
    class: "5A",
    teacher: "Nusrat Jahan",
  },
  {
    id: 7,
    subject: "Geography",
    class: "6A",
    teacher: "Nusrat Jahan",
  },
  {
    id: 8,
    subject: "Physics",
    class: "6B",
    teacher: "Prof. Ahmed Hossain",
  },
  {
    id: 9,
    subject: "Chemistry",
    class: "6C",
    teacher: "Fatema Begum",
  },
  {
    id: 10,
    subject: "Biology",
    class: "4B",
    teacher: "Mohammad Hasan",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Mathematics",
    class: "1A",
    teacher: "Md. Abdul Rahman",
    date: "2025-01-15",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Karim Uddin",
    date: "2025-01-16",
  },
  {
    id: 3,
    subject: "Bengali",
    class: "3A",
    teacher: "Dr. Selina Begum",
    date: "2025-01-17",
  },
  {
    id: 4,
    subject: "General Science",
    class: "1B",
    teacher: "Dr. Mohammad Ali",
    date: "2025-01-18",
  },
  {
    id: 5,
    subject: "Islamic Studies",
    class: "4A",
    teacher: "Rashida Khatun",
    date: "2025-01-19",
  },
  {
    id: 6,
    subject: "History",
    class: "5A",
    teacher: "Nusrat Jahan",
    date: "2025-01-20",
  },
  {
    id: 7,
    subject: "Geography",
    class: "6A",
    teacher: "Nusrat Jahan",
    date: "2025-01-21",
  },
  {
    id: 8,
    subject: "Physics",
    class: "6B",
    teacher: "Prof. Ahmed Hossain",
    date: "2025-01-22",
  },
  {
    id: 9,
    subject: "Chemistry",
    class: "6C",
    teacher: "Fatema Begum",
    date: "2025-01-23",
  },
  {
    id: 10,
    subject: "Biology",
    class: "4B",
    teacher: "Mohammad Hasan",
    date: "2025-01-24",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Mathematics",
    class: "1A",
    teacher: "Md. Abdul Rahman",
    dueDate: "2025-01-10",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Karim Uddin",
    dueDate: "2025-01-11",
  },
  {
    id: 3,
    subject: "Bengali",
    class: "3A",
    teacher: "Dr. Selina Begum",
    dueDate: "2025-01-12",
  },
  {
    id: 4,
    subject: "General Science",
    class: "1B",
    teacher: "Dr. Mohammad Ali",
    dueDate: "2025-01-13",
  },
  {
    id: 5,
    subject: "Islamic Studies",
    class: "4A",
    teacher: "Rashida Khatun",
    dueDate: "2025-01-14",
  },
  {
    id: 6,
    subject: "History",
    class: "5A",
    teacher: "Nusrat Jahan",
    dueDate: "2025-01-15",
  },
  {
    id: 7,
    subject: "Geography",
    class: "6A",
    teacher: "Nusrat Jahan",
    dueDate: "2025-01-16",
  },
  {
    id: 8,
    subject: "Physics",
    class: "6B",
    teacher: "Prof. Ahmed Hossain",
    dueDate: "2025-01-17",
  },
  {
    id: 9,
    subject: "Chemistry",
    class: "6C",
    teacher: "Fatema Begum",
    dueDate: "2025-01-18",
  },
  {
    id: 10,
    subject: "Biology",
    class: "4B",
    teacher: "Mohammad Hasan",
    dueDate: "2025-01-19",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Mathematics",
    class: "1A",
    teacher: "Md. Abdul Rahman",
    student: "Arif Hossain",
    date: "2025-01-15",
    type: "exam",
    score: 85,
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Karim Uddin",
    student: "Fatima Akter",
    date: "2025-01-16",
    type: "assignment",
    score: 92,
  },
  {
    id: 3,
    subject: "Bengali",
    class: "3A",
    teacher: "Dr. Selina Begum",
    student: "Rakib Ahmed",
    date: "2025-01-17",
    type: "exam",
    score: 88,
  },
  {
    id: 4,
    subject: "General Science",
    class: "1B",
    teacher: "Dr. Mohammad Ali",
    student: "Nusrat Jahan",
    date: "2025-01-18",
    type: "CT",
    score: 90,
  },
  {
    id: 5,
    subject: "Islamic Studies",
    class: "4A",
    teacher: "Rashida Khatun",
    student: "Sadia Rahman",
    date: "2025-01-19",
    type: "RC",
    score: 95,
  },
  {
    id: 6,
    subject: "History",
    class: "5A",
    teacher: "Nusrat Jahan",
    student: "Tahmid Hasan",
    date: "2025-01-20",
    type: "exam",
    score: 87,
  },
  {
    id: 7,
    subject: "Geography",
    class: "6A",
    teacher: "Nusrat Jahan",
    student: "Rashida Begum",
    date: "2025-01-21",
    type: "project",
    score: 91,
  },
  {
    id: 8,
    subject: "Physics",
    class: "6B",
    teacher: "Prof. Ahmed Hossain",
    student: "Karim Uddin",
    date: "2025-01-22",
    type: "exam",
    score: 89,
  },
  {
    id: 9,
    subject: "Chemistry",
    class: "6C",
    teacher: "Fatema Begum",
    student: "Nasrin Akter",
    date: "2025-01-23",
    type: "exam",
    score: 93,
  },
  {
    id: 10,
    subject: "Biology",
    class: "4B",
    teacher: "Mohammad Hasan",
    student: "Mohammad Ali",
    date: "2025-01-24",
    type: "exam",
    score: 86,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Dhaka Zoo Visit",
    class: "1A",
    date: "2025-01-25",
    startTime: "10:00",
    endTime: "15:00",
  },
  {
    id: 2,
    title: "National Museum Trip",
    class: "2A",
    date: "2025-01-26",
    startTime: "09:00",
    endTime: "14:00",
  },
  {
    id: 3,
    title: "Cox's Bazar Beach Trip",
    class: "3A",
    date: "2025-01-27",
    startTime: "08:00",
    endTime: "18:00",
  },
  {
    id: 4,
    title: "Liberation War Museum",
    class: "4A",
    date: "2025-01-28",
    startTime: "10:00",
    endTime: "13:00",
  },
  {
    id: 5,
    title: "Cultural Program",
    class: "5A",
    date: "2025-01-29",
    startTime: "14:00",
    endTime: "17:00",
  },
  {
    id: 6,
    title: "Science Fair",
    class: "1B",
    date: "2025-01-30",
    startTime: "10:00",
    endTime: "16:00",
  },
  {
    id: 7,
    title: "Botanical Garden Visit",
    class: "2B",
    date: "2025-01-31",
    startTime: "09:00",
    endTime: "14:00",
  },
  {
    id: 8,
    title: "Cricket Tournament",
    class: "3B",
    date: "2025-02-01",
    startTime: "08:00",
    endTime: "12:00",
  },
  {
    id: 9,
    title: "Art & Craft Exhibition",
    class: "4B",
    date: "2025-02-02",
    startTime: "10:00",
    endTime: "15:00",
  },
  {
    id: 10,
    title: "Annual Sports Day",
    class: "5B",
    date: "2025-02-03",
    startTime: "08:00",
    endTime: "16:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "Mathematics Exam Schedule for Class 4A",
    class: "4A",
    date: "2025-09-19",
  },
  {
    id: 2,
    title: "Bengali Language Test for Class 3A",
    class: "3A",
    date: "2025-09-20",
  },
  {
    id: 3,
    title: "Science Project Submission for Class 3B",
    class: "3B",
    date: "2025-09-21",
  },
  {
    id: 4,
    title: "History Assignment Due for Class 6A",
    class: "6A",
    date: "2025-09-22",
  },
  {
    id: 5,
    title: "Islamic Studies Quiz for Class 8C",
    class: "8C",
    date: "2025-09-23",
  },
  {
    id: 6,
    title: "English Literature Test for Class 2A",
    class: "2A",
    date: "2025-09-24",
  },
  {
    id: 7,
    title: "Physics Lab Report for Class 4C",
    class: "4C",
    date: "2025-09-25",
  },
  {
    id: 8,
    title: "Geography Field Trip for Class 4B",
    class: "4B",
    date: "2025-09-26",
  },
  {
    id: 9,
    title: "Chemistry Practical Exam for Class 3C",
    class: "3C",
    date: "2025-09-27",
  },
  {
    id: 10,
    title: "Biology Project Presentation for Class 1C",
    class: "1C",
    date: "2025-09-28",
  },
];

export const calendarEvents = [
  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 8, 19, 8, 0),
    end: new Date(2025, 8, 19, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 8, 19, 9, 0),
    end: new Date(2025, 8, 19, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 8, 19, 10, 0),
    end: new Date(2025, 8, 19, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 8, 19, 11, 0),
    end: new Date(2025, 8, 19, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 8, 19, 13, 0),
    end: new Date(2025, 8, 19, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 8, 19, 14, 0),
    end: new Date(2025, 8, 19, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 8, 20, 9, 0),
    end: new Date(2025, 8, 20, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 8, 20, 10, 0),
    end: new Date(2025, 8, 20, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 8, 20, 11, 0),
    end: new Date(2025, 8, 20, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2025, 8, 20, 14, 0),
    end: new Date(2025, 8, 20, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 8, 21, 8, 0),
    end: new Date(2025, 8, 21, 8, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 8, 21, 10, 0),
    end: new Date(2025, 8, 21, 10, 45),
  },

  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 8, 21, 13, 0),
    end: new Date(2025, 8, 21, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 8, 21, 14, 0),
    end: new Date(2025, 8, 21, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 8, 22, 9, 0),
    end: new Date(2025, 8, 22, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 8, 22, 10, 0),
    end: new Date(2025, 8, 22, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 8, 22, 11, 0),
    end: new Date(2025, 8, 22, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2025, 8, 22, 14, 0),
    end: new Date(2025, 8, 22, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 8, 23, 8, 0),
    end: new Date(2025, 8, 23, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 8, 23, 9, 0),
    end: new Date(2025, 8, 23, 9, 45),
  },

  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 8, 23, 11, 0),
    end: new Date(2025, 8, 23, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 8, 23, 13, 0),
    end: new Date(2025, 8, 23, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 8, 23, 14, 0),
    end: new Date(2025, 8, 23, 14, 45),
  },
];